### ISSUE TITLE
[web-frontend-trend]  banner error

### ISSUE THREAD

**Issue by byungmin12** [folloca/Web-Frontend#16]
> ## Description
setInterval 사용시 깜빡임 문제

> ## Due Date

> ## TODO
- [ ] Error

> ## ETC

https://user-images.githubusercontent.com/79984280/205650593-3d501d61-f926-4d31-829c-ce8d67979598.mov

영상을 보시면 아시겠지만 배너가 바뀌면 다른애들도 다 깜빡거리는 현상이 발생합니다.
문제는 setInterval이 한 바퀴가 다 돌면 더 이상 깜빡거리지가 않아요 .. 도움 좀 ㅠ  
@reemrev21

**Comment by reemrev21** [comment]
헉.. 죄송해요 확인이 늦었네요.. 참고하실 블로그 몇 개 첨부 했고 혹시 폰트 적용하셨으면 두번째것도 참고해보세요 
자세한 이야기는 월요일에 나누어봐요 !
Nextjs에서 styled-components 깜빡임 현상
https://minhyeong-jang.github.io/2019/12/12/nextjs-sc-twinkling 
Next.js에서 Styled-components사용할 때 그리고 GlobalStyle의 함정 (feat.Flickering&Font)
https://velog.io/@sv002/Next.js%EC%99%80-Styled-components-%EA%B7%B8%EB%A6%AC%EA%B3%A0-GlobalStyle%EC%9D%98-%ED%95%A8%EC%A0%95-feat.FlickeringFont
